# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
inputs:
  # Filepath of generated metrics (relative to repository root)
  filename:
    description: Path of SVG image output
    default: github-metrics.svg

  # Optimize SVG image with SVGO  (minify and remove useless attributes and spaces)
  # Some templates may not support this option
  optimize:
    description: Optimize SVG image
    default: yes
    
    # Coding habits plugin
  # Search in your recent activity what've recently did and deduce facts/charts
  plugin_habits:
    description: Enable coding habits metrics
    default: no
    
name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  push: {branches: "master"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: tapaafandi
          template: classic
          base: header, activity
          config_timezone: Asia/Jakarta
          plugin_languages: yes
          plugin_posts: yes
          plugin_posts_limit: 4
          plugin_posts_source: dev.to
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_tweets: yes
          plugin_tweets_limit: 2
