name: Metrics
on:
  # Schedule updates
  schedule: "0 * * * *"
  push: "master"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: tapaafandi/metrics@latest
        with:
          filename: metrics.svg
          token: $secrets.METRICS_TOKEN
          committer_token: $secrets.GITHUB_TOKEN
          base: "header, repositories"

          # Options
          user: tapaafandi
          template: classic
          config_timezone: Asia/Jakarta
          plugin_languages: yes
          plugin_posts: yes
          plugin_posts_limit: 4
          plugin_posts_source: dev.to
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_tweets: yes
          plugin_tweets_limit: 2
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
